version: '3.8'

services:

  backend:
    build: ./back
    ports:
      - 8000:8000
    volumes:
      - ./back:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./front
    volumes:
      - './front:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
