version: '3.9'

services:

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  database:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
